# Kolom dataset → (kode ISO, nama tampilan). us_dollar_to_usd sengaja diabaikan.
CURRENCY_COLUMNS = {
    "chinese_yuan_to_usd": ("CNY", "Yuan China"),
    "euro_to_usd": ("EUR", "Euro"),
    "japanese_yen_to_usd": ("JPY", "Yen Jepang"),
    "uk_pound_to_usd": ("GBP", "Pound Inggris"),
    "algerian_dinar_to_usd": ("DZD", "Dinar Algeria"),
    "australian_dollar_to_usd": ("AUD", "Dolar Australia"),
    "bahrain_dinar_to_usd": ("BHD", "Dinar Bahrain"),
    "botswana_pula_to_usd": ("BWP", "Pula Botswana"),
    "brazilian_real_to_usd": ("BRL", "Real Brasil"),
    "brunei_dollar_to_usd": ("BND", "Dolar Brunei"),
    "canadian_dollar_to_usd": ("CAD", "Dolar Kanada"),
    "chilean_peso_to_usd": ("CLP", "Peso Chile"),
    "colombian_peso_to_usd": ("COP", "Peso Kolombia"),
    "czech_koruna_to_usd": ("CZK", "Koruna Ceko"),
    "danish_krone_to_usd": ("DKK", "Krone Denmark"),
    "hungarian_forint_to_usd": ("HUF", "Forint Hungaria"),
    "icelandic_krona_to_usd": ("ISK", "Krona Islandia"),
    "indian_rupee_to_usd": ("INR", "Rupee India"),
    "indonesian_rupiah_to_usd": ("IDR", "Rupiah Indonesia"),
    "iranian_rial_to_usd": ("IRR", "Rial Iran"),
    "israeli_new_shekel_to_usd": ("ILS", "Shekel Israel"),
    "kazakhstani_tenge_to_usd": ("KZT", "Tenge Kazakhstan"),
    "korean_won_to_usd": ("KRW", "Won Korea"),
    "kuwaiti_dinar_to_usd": ("KWD", "Dinar Kuwait"),
    "libyan_dinar_to_usd": ("LYD", "Dinar Libya"),
    "malaysian_ringgit_to_usd": ("MYR", "Ringgit Malaysia"),
    "mauritian_rupee_to_usd": ("MUR", "Rupee Mauritius"),
    "mexican_peso_to_usd": ("MXN", "Peso Meksiko"),
    "nepalese_rupee_to_usd": ("NPR", "Rupee Nepal"),
    "new_zealand_dollar_to_usd": ("NZD", "Dolar Selandia Baru"),
    "norwegian_krone_to_usd": ("NOK", "Krone Norwegia"),
    "omani_rial_to_usd": ("OMR", "Rial Oman"),
    "pakistani_rupee_to_usd": ("PKR", "Rupee Pakistan"),
    "peruvian_sol_to_usd": ("PEN", "Sol Peru"),
    "philippine_peso_to_usd": ("PHP", "Peso Filipina"),
    "polish_zloty_to_usd": ("PLN", "Zloty Polandia"),
    "qatari_riyal_to_usd": ("QAR", "Riyal Qatar"),
    "russian_ruble_to_usd": ("RUB", "Rubel Rusia"),
    "saudi_arabian_riyal_to_usd": ("SAR", "Riyal Saudi"),
    "singapore_dollar_to_usd": ("SGD", "Dolar Singapura"),
    "south_african_rand_to_usd": ("ZAR", "Rand Afrika Selatan"),
    "sri_lankan_rupee_to_usd": ("LKR", "Rupee Sri Lanka"),
    "swedish_krona_to_usd": ("SEK", "Krona Swedia"),
    "swiss_franc_to_usd": ("CHF", "Franc Swiss"),
    "thai_baht_to_usd": ("THB", "Baht Thailand"),
    "trinidadian_dollar_to_usd": ("TTD", "Dolar Trinidad"),
    "tunisian_dinar_to_usd": ("TND", "Dinar Tunisia"),
    "uae_dirham_to_usd": ("AED", "Dirham UEA"),
    "uruguayan_peso_to_usd": ("UYU", "Peso Uruguay"),
    "bolivar_fuerte_to_usd": ("VES", "Bolivar Venezuela"),
}
